// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzmihnphnaphlhzhsgdu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6bWlobnBobmFwaGxoemhzZ2R1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5OTAxODcsImV4cCI6MjA2OTU2NjE4N30.x-v0B6M6MDAXMK8xa62UdlR2WjBn7dRDtr0qJwW9nFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});